import {useEffect,useState} from 'react'
import {useDevelopmentLiveRefresh} from '../../../lib/development-live-refresh'
import {Activity,Check,CheckCircle2,ChevronRight,MousePointer2,Settings2,ShieldCheck,Zap,X} from 'lucide-react'
import {diagnosticsApi as api} from '../data/diagnostics.api'
import {AccessibleDialog} from '../../../components/system/AccessibleDialog'
import {StaleState} from '../../../components/system/FrontendStates'
import {TrackingPageHead as PageHead,TrackingStat as Stat} from '../ui/DiagnosticsPrimitives'

export default function DiagnosticsPage(){
 const [data,setData]=useState<any>(null)
 const [selected,setSelected]=useState('')
 const [replays,setReplays]=useState<string[]>([])
 const [scan,setScan]=useState<any>(null)
 const [configOpen,setConfigOpen]=useState(false)
 const [busy,setBusy]=useState('')
 const [notice,setNotice]=useState('')
 const [uncertain,setUncertain]=useState(false)
 const load=()=>api.diagnostics().then((r:any)=>{setData(r);if(!selected&&r.issues?.[0])setSelected(r.issues[0].key)}).catch(()=>null)
 useEffect(()=>{load()},[])
 useDevelopmentLiveRefresh(()=>load())
 const issueMap:any={duplicate_conversions:['Duplicate conversions','Duplicate delivery/audit evidence detected.'],missing_click_ids:['Missing click IDs','A share of active click sessions lacks usable advertising identifiers.'],delivery_failures:['Delivery failures','Dead-letter signal deliveries need investigation or replay.'],connector_health:['Connector health','A connected provider is reporting degraded health.'],schema_mismatch:['Schema mismatch','Quarantined events require field or schema correction.']}
 const issues=(data?.issues||[]).map((x:any)=>({...x,title:issueMap[x.key]?.[0]||String(x.key).replaceAll('_',' '),description:issueMap[x.key]?.[1]||'Operational issue detected.'}))
 const current=issues.find((x:any)=>x.key===selected)||issues[0]
 const replay=async(key:string)=>{setBusy('replay');setNotice('');setUncertain(false);try{await api.replayDiagnostic(key);setReplays(x=>x.includes(key)?x:[...x,key]);setNotice('Replay accepted by the backend.')}catch(e:any){const cause=String(e?.details?.cause||'');if(cause==='timeout'||cause==='network'){setUncertain(true);setNotice('The backend did not confirm whether replay was accepted. Refresh diagnostics before replaying again.')}else setNotice(e?.message||'Diagnostic replay could not be accepted.')}finally{setBusy('')}}
 const runScan=async()=>{setBusy('scan');setNotice('');setUncertain(false);try{const r:any=await api.runDiagnosticsScan();setScan(r);setNotice('Diagnostics scan completed and confirmed.');await load()}catch(e:any){const cause=String(e?.details?.cause||'');if(cause==='timeout'||cause==='network'){setUncertain(true);setNotice('The backend did not confirm whether the diagnostics scan completed. Refresh diagnostics before starting another scan.')}else setNotice(e?.message||'Diagnostics scan could not be completed.')}finally{setBusy('')}}
 return <><PageHead crumb="Tracking / Diagnostics" title="Tracking & data quality diagnostics" sub="Inspect live delivery, identity, queue and connector health instead of relying on static quality scores." action={busy==='scan'?'Scanning…':'Run full scan'} onAction={runScan}/>
 {uncertain&&notice?<StaleState title="Diagnostics action needs reconciliation" description={notice} action={{label:'Refresh diagnostics',onClick:load}}/>:notice&&<div className={'delivery-notice '+(notice.toLowerCase().includes('could not')?'error':'ok')} role={notice.toLowerCase().includes('could not')?'alert':'status'}>{notice.toLowerCase().includes('could not')?<ShieldCheck/>:<CheckCircle2/>}<span>{notice}</span></div>}
 {scan&&<div className="delivery-notice ok"><CheckCircle2/><span>Scan {scan.id} completed · {scan.deadLetter} dead-letter deliveries · {scan.connectorIssues} connector issues · {scan.unmatchedAttribution} unmatched attribution events.</span></div>}
 <div className="stats-grid"><Stat label="Signal quality score" value={data?String(data.score)+'/100':'—'} sub="Derived from current workspace state" Icon={ShieldCheck}/><Stat label="Duplicate evidence" value={data?String(data.duplicateRate)+'%':'—'} sub="Audit/delivery evidence" Icon={Zap}/><Stat label="Click-ID coverage" value={data?String(data.clickIdCoverage)+'%':'—'} sub="Active first-party click sessions" Icon={MousePointer2}/><Stat label="Delivery rate" value={data?String(data.deliveryRate)+'%':'—'} sub="Persisted provider deliveries" Icon={Activity}/></div>
 <div className="diagnostic-ops-layout"><div className="app-panel diagnostic-issue-list"><div className="panel-head"><div><h3>Detected issues</h3><p>Generated from live workspace state</p></div><span className={issues.length?'status':'healthy'}>{issues.length} open</span></div>{issues.length?issues.map((x:any)=><button key={x.key+(x.connector||'')} className={selected===x.key?'selected':''} onClick={()=>setSelected(x.key)}><Activity/><div><b>{x.title}</b><small>{x.connector||x.affected||x.affectedPercent||x.quarantined||'Workspace signal issue'}</small></div><span className={String(x.severity||'info').toLowerCase()}>{x.severity||'info'}</span><ChevronRight/></button>):<div className="empty-delivery-state"><CheckCircle2/><div><b>No active diagnostic issues</b><small>Current delivery, connector and attribution checks are within configured thresholds.</small></div></div>}</div>
 <div className="app-panel diagnostic-detail">{current?<><div className="panel-head"><div><h3>{current.title}</h3><p>{current.description}</p></div><span className={'diag-severity '+String(current.severity||'info').toLowerCase()}>{current.severity||'Info'}</span></div><div className="diagnostic-evidence">{[['Issue key',current.key],['Connector',current.connector||'—'],['Affected',String(current.affected??current.affectedPercent??current.quarantined??'—')],['Status',current.status||'Open']].map(x=><article key={x[0]}><span>{x[0]}</span><b>{x[1]}</b></article>)}</div><div className="diagnostic-actions"><button onClick={()=>setConfigOpen(true)}>Open configuration</button><button className="primary" disabled={busy==='replay'} onClick={()=>replay(current.key)}>{replays.includes(current.key)?<><Check/>Replay queued</>:<>Replay affected events</>}</button></div></>:<div className="empty-delivery-state"><ShieldCheck/><div><b>Workspace healthy</b><small>No active issue selected.</small></div></div>}</div></div>
 {configOpen&&<AccessibleDialog ariaLabel="Diagnostic configuration guidance" onClose={()=>setConfigOpen(false)}><div className="connector-card"><div className="connector-modal-head"><div><Settings2/><div><b>Diagnostic configuration guidance</b><small>{current?.title||'Workspace diagnostics'}</small></div></div><button onClick={()=>setConfigOpen(false)}><X/></button></div><div className="connector-step"><div className="setting-line"><span>Delivery queue</span><b>{data?.queue?.available===false?'Unavailable':'Connected'}</b></div><div className="setting-line"><span>Recommended action</span><b>{current?.key==='missing_click_ids'?'Review Tracking settings and click-ID persistence':current?.key==='connector_health'?'Reconnect or refresh the affected integration':current?.key==='delivery_failures'?'Review Delivery Center / DLQ':'Review event rules and source mappings'}</b></div><button onClick={()=>setConfigOpen(false)}>Close</button></div></div></AccessibleDialog>}</>
}
