import {useEffect,useState} from 'react'
import {ArrowRight,CheckCircle2,ChevronRight,CircleDollarSign,MessageCircle,PhoneCall,RadioTower,ShieldCheck,Target,X} from 'lucide-react'
import {offlineAttributionApi} from '../data/offline-attribution.api'
import {AccessibleDialog} from '../../../components/system/AccessibleDialog'
import {LoadingState} from '../../../components/system/FrontendStates'
import {useDirtyWork} from '../../../lib/dirty-work'

function PageHead({crumb,title,sub,action,onAction}:{crumb:string,title:string,sub:string,action?:string,onAction?:()=>void}){return <div className="page-head"><div><span>{crumb}</span><h1 tabIndex={-1}>{title}</h1><p>{sub}</p></div>{action&&<button className="app-primary" onClick={onAction}>{action}</button>}</div>}
function Stat({label,value,sub,Icon}:{label:string,value:string,sub:string,Icon:any}){return <article className="stat"><div><span>{label}</span><Icon/></div><strong>{value}</strong><small>{sub}</small></article>}

export default function OfflineAttributionPage(){
 const [data,setData]=useState<any>({callAttribution:{},whatsapp:{},attribution:{},rules:[],templates:[]})
 const [ctwa,setCtwa]=useState<any>({available:false,stats:{},items:[]})
 const [selected,setSelected]=useState('')
 const [builder,setBuilder]=useState(false)
 const [busy,setBusy]=useState('')
 const [loading,setLoading]=useState(true)
 const [notice,setNotice]=useState<{kind:'ok'|'error'|'unknown'|'',text:string}>({kind:'',text:''})
 const [draft,setDraft]=useState<any>({conversion:'',source:'',match:'',identifier:''})
 useDirtyWork({key:'offline-attribution-rule-draft',label:'Offline attribution rule',dirty:builder,scope:'feature'})
 const load=async()=>{setLoading(true);try{const [r,c]:any=await Promise.all([offlineAttributionApi.load(),offlineAttributionApi.ctwa().catch(()=>({available:false,stats:{},items:[]}))]);setData(r);setCtwa(c);const rules=r.rules||[];setSelected((x:string)=>x&&rules.some((i:any)=>i.id===x)?x:(rules[0]?.id||''));setNotice(n=>n.kind==='error'?{kind:'',text:''}:n)}catch(e:any){setNotice({kind:'error',text:e?.message||'Offline attribution could not be loaded. Existing attribution evidence was preserved.'})}finally{setLoading(false)}}
 useEffect(()=>{load()},[])
 const current=(data.rules||[]).find((x:any)=>x.id===selected)||data.rules?.[0]
 const callEvents=Number(data.callAttribution?.events||0)
 const waMessages=Number(data.whatsapp?.messages||0)
 const matched=Number(data.attribution?.matchedEvents||0)
 const unmatched=Number(data.attribution?.unmatchedEvents||0)
 const matchRate=Number(data.attribution?.matchRate||0)
 const create=async(e:any)=>{e.preventDefault();const fd=new FormData(e.currentTarget);setBusy('create');setNotice({kind:'',text:''});try{const r:any=await offlineAttributionApi.createRule({conversion:String(fd.get('conversion')||''),source:String(fd.get('source')||''),match:String(fd.get('match')||''),identifier:String(fd.get('identifier')||''),destination:Array.from(fd.getAll('destination')).map(String)});setBuilder(false);setNotice({kind:'ok',text:'Offline attribution rule created after backend confirmation.'});await load();if(r?.item?.id)setSelected(r.item.id)}catch(err:any){const cause=String(err?.details?.cause||'');setNotice(cause==='timeout'||cause==='network'?{kind:'unknown',text:'The rule-creation outcome is unknown. Refresh authoritative attribution state before creating the same rule again.'}:{kind:'error',text:err?.message||'Offline rule could not be created.'})}finally{setBusy('')}}
 const toggle=async()=>{if(!current)return;setBusy('toggle');setNotice({kind:'',text:''});try{await offlineAttributionApi.toggleRule(current.id,current.status==='paused');setNotice({kind:'ok',text:current.status==='paused'?'Offline rule enabled after backend confirmation.':'Offline rule paused after backend confirmation.'});await load()}catch(e:any){const cause=String(e?.details?.cause||'');setNotice(cause==='timeout'||cause==='network'?{kind:'unknown',text:'The rule-status outcome is unknown. Refresh authoritative attribution state before repeating the change.'}:{kind:'error',text:e?.message||'Offline rule status could not be changed.'})}finally{setBusy('')}}
 const test=async(e:any)=>{e.preventDefault();if(!current)return;const fd=new FormData(e.currentTarget);setBusy('test');setNotice({kind:'',text:''});try{const r:any=await offlineAttributionApi.testRule({ruleId:current.id,customerId:String(fd.get('customerId')||''),phone:String(fd.get('phone')||''),email:String(fd.get('email')||''),gclid:String(fd.get('gclid')||''),fbclid:String(fd.get('fbclid')||''),value:Number(fd.get('value')||0),currency:'INR'});setNotice({kind:'ok',text:'Test event recorded with status '+r.status+(r.matchMethod?' via '+r.matchMethod:'')+'.'});await load()}catch(err:any){const cause=String(err?.details?.cause||'');setNotice(cause==='timeout'||cause==='network'?{kind:'unknown',text:'The offline test outcome is unknown. Refresh authoritative attribution state before submitting the same test again.'}:{kind:'error',text:err?.message||'Offline attribution test failed.'})}finally{setBusy('')}}
 const applyTemplate=(x:any)=>{setDraft({conversion:x.conversion||'',source:x.source||'',match:x.match||'',identifier:x.identifier||''});setBuilder(true)}
 return <><PageHead crumb="AdSync / Offline Attribution" title="Calls, WhatsApp & offline revenue" sub="Bridge digital acquisition with real call, WhatsApp, CRM and offline conversion events using persisted first-party identity rules." action="New offline rule" onAction={()=>{setDraft({conversion:'',source:'',match:'',identifier:''});setBuilder(true)}}/>
 {loading&&!(data.rules||[]).length&&<LoadingState title="Loading offline attribution" description="Reading call, WhatsApp, rule and attribution evidence."/>}
 {notice.text&&<div className={'delivery-notice '+(notice.kind==='error'?'error':notice.kind==='unknown'?'warning':'ok')} role={notice.kind==='error'?'alert':'status'}>{notice.kind==='ok'?<CheckCircle2/>:<ShieldCheck/>}<span>{notice.text}</span>{notice.kind!=='ok'&&<button onClick={load}>Refresh authoritative state</button>}</div>}
 <div className="stats-grid"><Stat label="Tracked calls" value={String(callEvents)} sub="Signed telephony events" Icon={PhoneCall}/><Stat label="WhatsApp messages" value={String(waMessages)} sub="Verified Cloud API inbound events" Icon={MessageCircle}/><Stat label="Matched offline events" value={data.attribution?.available?String(matched):'—'} sub={data.attribution?.available?matchRate+'% match rate':'Attribution store unavailable'} Icon={Target}/><Stat label="Unmatched queue" value={data.attribution?.available?String(unmatched):'—'} sub="Held from signal return" Icon={CircleDollarSign}/></div>
 <div className="matchback-layout"><div className="app-panel matchback-list"><div className="panel-head"><div><h3>Offline attribution rules</h3><p>Persisted source → identity match → destination configuration</p></div><span className="healthy">{(data.rules||[]).length} configured</span></div>{(data.rules||[]).length?(data.rules||[]).map((x:any)=><button key={x.id} className={selected===x.id?'selected':''} onClick={()=>setSelected(x.id)}><RadioTower/><div><b>{x.conversion}</b><small>{x.source} · {x.identifier}</small></div><span className={x.status==='active'?'healthy':'status'}>{x.status}</span><ChevronRight/></button>):<div className="empty-delivery-state"><RadioTower/><div><b>No offline attribution rules yet</b><small>Create a rule or use a suggested template. No example rule is treated as customer data.</small></div></div>}</div>
 <div className="app-panel matchback-detail">{current?<><div className="panel-head"><div><h3>{current.conversion}</h3><p>{current.source} → {(current.destination||[]).join(', ')}</p></div><span className={current.status==='active'?'healthy':'status'}>{current.status}</span></div><div className="site-detail-grid">{[['Matching logic',current.match],['Identifier',current.identifier],['Last test',current.lastTestAt?new Date(current.lastTestAt).toLocaleString():'Never'],['Last test status',current.lastTestStatus||'—'],['Last match method',current.lastTestMethod||'—']].map(x=><div key={x[0]}><span>{x[0]}</span><b>{String(x[1])}</b></div>)}</div><div className="approval-actions"><button disabled={busy==='toggle'} onClick={toggle}>{busy==='toggle'?'Saving…':current.status==='paused'?'Enable rule':'Pause rule'}</button></div><form className="offline-test-form" onSubmit={test}><div className="panel-head"><div><h3>Test identity reconciliation</h3><p>Send a real assisted-event test through the attribution store.</p></div></div><div className="two-col"><label>Customer ID<input name="customerId" placeholder="customer_123"/></label><label>Phone<input name="phone" placeholder="+91..."/></label><label>Email<input name="email" type="email" placeholder="lead@example.com"/></label><label>GCLID<input name="gclid" placeholder="optional click ID"/></label></div><div className="two-col"><label>FBCLID<input name="fbclid" placeholder="optional Meta click ID"/></label><label>Value (INR)<input name="value" type="number" min="0" defaultValue="0"/></label></div><button className="approve" disabled={busy==='test'||current.status==='paused'}>{busy==='test'?'Testing…':'Send offline test event'}</button></form></>:<div className="empty-delivery-state"><RadioTower/><div><b>Select or create an offline attribution rule</b></div></div>}</div></div>
 {(data.templates||[]).length>0&&<div className="app-panel"><div className="panel-head"><div><h3>Suggested offline templates</h3><p>Configuration examples only; they do not represent workspace activity.</p></div></div><div className="template-grid">{(data.templates||[]).map((x:any)=><button key={x.conversion} onClick={()=>applyTemplate(x)}><RadioTower/><div><b>{x.conversion}</b><small>{x.source} · {x.identifier}</small></div><span>{(x.destination||[]).join(', ')}</span></button>)}</div></div>}
 <div className="app-panel"><div className="panel-head"><div><h3>Click-to-WhatsApp attribution</h3><p>Meta CTWA referral metadata → WhatsApp conversation → downstream value</p></div><span className={Number(ctwa.stats?.referredMessages||0)>0?'healthy':'warning'}>{Number(ctwa.stats?.attributedClicks||0)} attributed clicks</span></div><div className="site-detail-grid">{[['Referred messages',ctwa.stats?.referredMessages||0],['Unique contacts',ctwa.stats?.uniqueContacts||0],['Attributed CTWA clicks',ctwa.stats?.attributedClicks||0],['Observed conversion value','₹'+Number(ctwa.stats?.conversionValue||0).toLocaleString('en-IN')]].map(x=><div key={x[0]}><span>{x[0]}</span><b>{String(x[1])}</b></div>)}</div>{(ctwa.items||[]).length?<div className="debug-event-list">{(ctwa.items||[]).slice(0,8).map((x:any)=><div className="developer-event-row" key={x.ctwaClid}><code>{x.ctwaClid}</code><span>{x.headline||x.sourceId||'Meta click-to-WhatsApp referral'} · {x.messages||0} message(s) · {x.contacts||0} contact(s)</span><strong>{Number(x.conversionValue||0)>0?'₹'+Number(x.conversionValue).toLocaleString('en-IN'):(x.lastActivity?new Date(x.lastActivity).toLocaleString():'No value yet')}</strong></div>)}</div>:<div className="empty-delivery-state"><MessageCircle/><div><b>No CTWA referral evidence yet</b><small>When Meta sends WhatsApp referral metadata, AceMarketing retains the CTWA click reference and attributes the resulting conversation without fabricating campaign performance.</small></div></div>}</div>
 <div className="two-col"><div className="app-panel"><div className="panel-head"><div><h3>Live call tracking</h3><p>Signed provider events feed lead and attribution context</p></div><span className={callEvents?'healthy':'warning'}>{callEvents?callEvents+' events':'No events yet'}</span></div><div className="match-flow"><div><span>1</span><b>Ad / source touch</b><small>Click/session identity retained</small></div><ArrowRight/><div><span>2</span><b>Inbound call</b><small>Signed webhook received</small></div><ArrowRight/><div><span>3</span><b>Lead context</b><small>Call outcome enriches profile</small></div><ArrowRight/><div><span>4</span><b>Attribution</b><small>Assisted event reconciled</small></div></div></div>
 <div className="app-panel"><div className="panel-head"><div><h3>WhatsApp identity bridge</h3><p>Cloud API events connected to the stitched journey</p></div><span className={waMessages?'healthy':'warning'}>{waMessages?waMessages+' messages':'No events yet'}</span></div><div className="freshness-card"><MessageCircle/><div><b>Verified inbound event</b><p>Meta signature verification, phone-number workspace routing, lead upsert and assisted attribution are handled before the event becomes workspace truth.</p></div></div><div className="freshness-card"><CircleDollarSign/><div><b>Revenue handoff</b><p>Downstream CRM or billing outcomes can reuse the same customer identity before Google/Meta signal return.</p></div></div></div></div>
 {builder&&<AccessibleDialog ariaLabel="New offline attribution rule" onClose={()=>setBuilder(false)}><form className="connector-card offline-builder" onSubmit={create}><div className="connector-modal-head"><div><RadioTower/><div><b>New offline attribution rule</b><small>Define a real source-to-identity-to-destination matching rule.</small></div></div><button type="button" aria-label="Close offline attribution rule" onClick={()=>setBuilder(false)}><X/></button></div><label>Conversion<input name="conversion" required defaultValue={draft.conversion} placeholder="Inbound Call"/></label><label>Source<input name="source" required defaultValue={draft.source} placeholder="Telephony"/></label><label>Matching method<input name="match" required defaultValue={draft.match} placeholder="phone + click/session reconciliation"/></label><label>Identifier<input name="identifier" required defaultValue={draft.identifier} placeholder="Phone / GCLID / FBCLID"/></label><fieldset><legend>Destinations</legend><label><input type="checkbox" name="destination" value="Google Ads" defaultChecked/>Google Ads</label><label><input type="checkbox" name="destination" value="Meta Ads" defaultChecked/>Meta Ads</label></fieldset><button disabled={busy==='create'}>{busy==='create'?'Creating…':'Create offline rule'}</button></form></AccessibleDialog>}</>
}
