-- Compatibility marker retained because this migration filename was introduced on main.
-- The executable tenant cell placement schema moved to 054_cell_placement.sql so each
-- migration sequence number has one authoritative implementation.
