export type DemoRequest = Record<string, FormDataEntryValue>

const getToken = () => typeof window !== 'undefined' ? window.localStorage.getItem('ace_token') : null

const request = async <T>(path: string, init?: RequestInit): Promise<T> => {
  const token=getToken()
  const response = await fetch(`/api${path}`, {
    headers: { 'Content-Type': 'application/json', ...(token ? { Authorization: `Bearer ${token}` } : {}), ...(init?.headers || {}) },
    ...init,
  })
  if (!response.ok) throw new Error(`API request failed: ${response.status}`)
  return response.json()
}

export const api = {
  health: () => request<{ ok: boolean; service: string }>('/health'),
  publicNavigation: () => request('/public/navigation'),
  publicIndustries: () => request('/public/industries'),
  publicAgents: () => request('/public/agents'),
  publicIntegrations: () => request('/public/integrations'),
  publicChallenges: () => request('/public/challenges'),
  publicCaseStudies: () => request('/public/case-studies'),
  publicResources: () => request('/public/resources'),
  launchpad: () => request('/launchpad'),
  saveLaunchpad: (payload: Record<string, unknown>) => request('/launchpad', { method: 'POST', body: JSON.stringify(payload) }),
  login: async (email: string, password: string) => {
    const result = await request<{ token: string; user: { email: string; role: string }; expiresIn: number }>('/auth/login', {
      method: 'POST',
      body: JSON.stringify({ email, password }),
    })
    if (typeof window !== 'undefined') window.localStorage.setItem('ace_token', result.token)
    return result
  },
  logout: () => { if (typeof window !== 'undefined') window.localStorage.removeItem('ace_token') },
  pricingRecommendation: (payload: Record<string, unknown>) => request<{ recommended: string[] }>('/pricing/recommend', { method: 'POST', body: JSON.stringify(payload) }),
  submitQuote: (payload: Record<string, unknown>) => request<{ id: string; status: string }>('/pricing/quote', { method: 'POST', body: JSON.stringify(payload) }),
  submitDemo: (payload: DemoRequest) =>
    request<{ id: string; status: string }>('/demo-requests', {
      method: 'POST',
      body: JSON.stringify(payload),
    }),
  overview: () => request('/workspace/overview'),
  integrations: () => request('/integrations'),
  events: () => request('/events'),
  adjustments: () => request('/adjustments'),
  applyAdjustment: (id: string) => request('/adjustments/apply', { method: 'POST', body: JSON.stringify({ id }) }),
  diagnostics: () => request('/diagnostics'),
  fraud: () => request('/fraud'),
  blockFraudPattern: (pattern: string) => request('/fraud/block', { method: 'POST', body: JSON.stringify({ pattern }) }),
  deepLinks: () => request('/deep-links'),
  activateDeepLink: (slug: string) => request('/deep-links/activate', { method: 'POST', body: JSON.stringify({ slug }) }),
  sites: () => request('/sites'),
  fingerprinting: () => request('/fingerprinting'),
  testFingerprint: (scenario: string) => request('/fingerprinting/test', { method: 'POST', body: JSON.stringify({ scenario }) }),
  testSite: (domain: string) => request('/sites/test', { method: 'POST', body: JSON.stringify({ domain }) }),
  replayDiagnostic: (issue: string) => request('/diagnostics/replay', { method: 'POST', body: JSON.stringify({ issue }) }),
  funnel: () => request('/funnel'),
  liveSync: () => request('/live-sync'),
  dataHub: () => request('/data-hub'),
  rebuildDataHub: () => request('/data-hub/rebuild', { method: 'POST', body: JSON.stringify({}) }),
  offlineAttribution: () => request('/offline-attribution'),
  matchback: () => request('/matchback'),
  reconcileMatchback: (rule: string) => request('/matchback/reconcile', { method: 'POST', body: JSON.stringify({ rule }) }),
  posStores: () => request('/pos-stores'),
  importPosBatch: (payload: Record<string, unknown>) => request('/pos-stores/import', { method: 'POST', body: JSON.stringify(payload) }),
  track: (payload: Record<string, unknown>) => request('/track', { method: 'POST', body: JSON.stringify(payload) }),
  journeys: () => request('/journeys'),
  identity: () => request('/identity'),
  models: () => request('/models'),
  runModel: (name: string) => request('/models/run', { method: 'POST', body: JSON.stringify({ name }) }),
  attribution: () => request('/attribution'),
  reports: () => request('/reports'),
  planner: () => request('/planner'),
  sendReportTest: (report: string) => request('/reports/send-test', { method: 'POST', body: JSON.stringify({ report }) }),
  agents: () => request('/agents'),
  routing: () => request('/routing'),
  testRoutingRule: (rule: string) => request('/routing/test', { method: 'POST', body: JSON.stringify({ rule }) }),
  followUps: () => request('/follow-ups'),
  completeFollowUp: (id: string) => request('/follow-ups/complete', { method: 'POST', body: JSON.stringify({ id }) }),
  qualificationCalls: () => request('/qualification-calls'),
  retryQualificationCall: (id: string) => request('/qualification-calls/retry', { method: 'POST', body: JSON.stringify({ id }) }),
  meetings: () => request('/meetings'),
  sendMeetingReminder: (id: string) => request('/meetings/remind', { method: 'POST', body: JSON.stringify({ id }) }),
  feedback: () => request('/feedback'),
  approvals: () => request('/approvals'),
  decideApproval: (id: string, decision: 'approved' | 'rejected') => request('/approvals/decision', { method: 'POST', body: JSON.stringify({ id, decision }) }),
  createAgent: (payload: Record<string, unknown>) => request('/agents/custom', { method: 'POST', body: JSON.stringify(payload) }),
  audiences: () => request('/audiences'),
  previewAudience: (payload: Record<string, unknown>) => request('/audiences/preview', { method: 'POST', body: JSON.stringify(payload) }),
  createAudience: (payload: Record<string, unknown>) => request('/audiences', { method: 'POST', body: JSON.stringify(payload) }),
  behavior: () => request('/behavior'),
  feed: () => request('/feed'),
  solutions: () => request('/solutions'),
  askAce: (question: string) => request('/ask-ace', { method: 'POST', body: JSON.stringify({ question }) }),
  connectIntegration: (connector: string) => request('/integrations/connect', { method: 'POST', body: JSON.stringify({ connector }) }),
  signalDeliveries: () => request('/signal-deliveries'),
  dispatchSignal: (payload: Record<string, unknown>) => request('/signal-deliveries/dispatch', { method: 'POST', body: JSON.stringify(payload) }),
  retrySignalDelivery: (id: string) => request('/signal-deliveries/retry', { method: 'POST', body: JSON.stringify({ id }) }),
  replaySignalDlq: () => request('/signal-deliveries/replay-dlq', { method: 'POST', body: JSON.stringify({}) }),
  connectorHealth: () => request('/connector-health'),
  monitoring: () => request('/monitoring'),
  alerts: () => request('/alerts'),
  resolveAlert: (id: string) => request('/alerts/resolve', { method: 'POST', body: JSON.stringify({ id }) }),
  signalConsole: () => request('/signal-console'),
  securityPosture: () => request('/security-posture'),
  resources: () => request('/resources'),
  caseStudies: () => request('/case-studies'),
  aiAction: () => request('/ai-action'),
  sourceNotes: () => request('/source-notes'),
  eventTemplates: () => request('/event-templates'),
  monitoringRules: () => request('/monitoring-rules'),
  saveConsent: (prefs: Record<string, boolean>) => request('/consent-preferences', { method: 'POST', body: JSON.stringify(prefs) }),
  settings: () => request('/settings'),
  workspaces: () => request('/workspaces'),
  webhookDeliveries: () => request('/webhooks/deliveries'),
  retryWebhook: (id: string) => request('/webhooks/retry', { method: 'POST', body: JSON.stringify({ id }) }),
  rotateWebhookSecret: () => request('/webhooks/secret/rotate', { method: 'POST', body: JSON.stringify({}) }),
  auditLog: () => request('/audit-log'),
  createApiKey: () => request('/api-keys', { method: 'POST', body: JSON.stringify({ name: 'workspace' }) }),
}
